version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-jessie-node

    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install django==2.0
      - run:
          command: |
            . venv/bin/activate
            python manage.py test
